AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Application template 
 
#Parameters:
#    FunctionNameSuffix:
#        Type: String
#        Default: "$FunctionSuffix"
  
Globals:
  Function:
    Timeout: 3

Resources:
  returnS3Buckets:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bucketlist.handler
      Runtime: nodejs10.x
      CodeUri: code/
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListAllMyBuckets"
            Resource: '*'
Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref BasicAWSApiGateway
            Path: /hello
            Method: GET       
      #DeploymentPreference:
          #Type: Linear10PercentEvery1Minute
          #Type: AllAtOnce
          #Hooks:
            #PreTraffic: !Ref preTrafficHook
      #Events:
       # Api:
        #  HttpPost:
         # Type: Api
          #Properties:
           # Path: /test
            #Method: post
            

  
