AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Application template 
  
Globals:
  Function:
    Timeout: 150
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  ApiFunction: # Adds a GET api endpoint at "/" to the ApiGatewayApi via an Api event
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /code
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        ApipostEvent:
          Type: Api
          Properties:
            Path: /code
            #Method: get
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: nodejs12.x
      Handler: index.handler
  ArchiveNotificationsData:
    Type: AWS::Serverless::Function
    Properties:
      #CodeUri: NotificationService/ArchiveNotification
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: '*'
            Resource: '*'
      #Events:
       # ApiEvent:
        #  Type: Api 
         # Properties:
          #  Path: /code/index.js
           # Method: get 
  ClearAllViewNotifications:
    Type: AWS::Serverless::Function
    Properties:
      #CodeUri: NotificationService/ClearNotification
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: '*'
            Resource: '*'
      #Events:
        #ClearNotification:
          #Type: Api 
          #Properties:
            #Path: /
            #Method: get
  GetNotifications:
    Type: AWS::Serverless::Function
    Properties:
      #CodeUri: NotificationService/FetchNotification
      Handler: index.handler
      Runtime: nodejs12.x
      #Tags:
        #Project: CYNC
        #Environment: DEV
       # LambdaId: DEV-lAMBDA
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: '*'
            Resource: '*'
      #Events:
        #FetchNotification:
          #Type: Api 
          #Properties:
            #Path: /
            #Method: get
  SaveNotifications:
    Type: AWS::Serverless::Function
    Properties:
      #CodeUri: NotificationService/SaveNotification
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: '*'
            Resource: '*'
      #Events:
        #SaveNotification:
          #Type: Api 
          #Properties:
            #Path: /
            #Method: get
  SendNotifications:
    Type: AWS::Serverless::Function
    Properties:
      #CodeUri: NotificationService/SendNotification
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: '*'
            Resource: '*'
      #Events:
        #SendNotification:
          #Type: Api 
          #Properties:
            #Path: /
            #Method: get
  ViewNotificationStatusUpdate:
    Type: AWS::Serverless::Function
    Properties:
      #CodeUri: NotificationService/UpdateStatusofViewNotification
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: '*'
            Resource: '*'
      #Events:
        #UpdateStatusofViewNotification:
          #Type: Api 
          #Properties:
            #Path: /
            #Method: get
